#!/bin/sh
set -e

# Apache gets grumpy about PID files pre-existing
[ -e ${HTTPD_PREFIX:-/usr/local/apache2}/logs/httpd.pid ] && rm -f ${HTTPD_PREFIX:-/usr/local/apache2}/logs/httpd.pid

exec httpd -DFOREGROUND